# Numpy (Arrays) Tutorial
NumPy, which stands for Numerical Python, is a library consisting of multidimensional array objects and a collection of routines for processing those arrays. Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.
### Installation:
`> pip install numpy`

`$ pip3 install numpy`

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5]) # declaring an array using list anotation
a

array([1, 2, 3, 4, 5])

In [3]:
b = np.array((8, 4, 7, 1, 9)) # declaring an array using tuple anotation
b

array([8, 4, 7, 1, 9])

### Basic Operations

In [4]:
# different mathematical operations can be perfomed on numpy array
a * 3 

array([ 3,  6,  9, 12, 15])

In [5]:
# mathematical operations between two arrays
a + b

array([ 9,  6, 10,  5, 14])

In [6]:
b - a

array([ 7,  2,  4, -3,  4])

In [7]:
a**2

array([ 1,  4,  9, 16, 25], dtype=int32)

### NumPy’s array class (ndarray)
The more important attributes of an ndarray object are:

- `ndarray.ndim`: the number of axes (dimensions) of the array. In the Python world, the number of dimensions is referred to as rank.
- `ndarray.shape`: the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the rank, or number of dimensions, ndim.
- `ndarray.size`: the total number of elements of the array. This is equal to the product of the elements of shape.
- `ndarray.dtype`: an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.
- `ndarray.itemsize`: the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.
- `ndarray.data`: the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.

In [8]:
a = np.array([1, 2, 3, 4, 5], dtype = float)
a

array([ 1.,  2.,  3.,  4.,  5.])

In [9]:
type(a)

numpy.ndarray

In [10]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a.dtype)
print(a.itemsize)    # bytes per element
print(a.size)        # size reports total number of elements in an Array.
print(a.shape)       # indicates that array has 5 elements along dimension zero in this case.

int32
4
6
(6,)


In [11]:
a.shape = (2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

### Indexing and Slicing

In [12]:
a = np.array([1, 2, 3, 4, 5])
# Array Indexing
a[0]

1

In [13]:
# Re-assigning values
a[0] = 50
a

array([50,  2,  3,  4,  5])

In [14]:
# assigning a float into an int32 array truncates the decimal part
a[0] = 5.8
a

array([5, 2, 3, 4, 5])

In [15]:
# Slicing for Arrays works like List Slicing
b[2:4]

array([7, 1])

In [16]:
b[-4:3]

array([4, 7])

In [17]:
b[::2]

array([8, 7, 9])

In [18]:
b[::-1]

array([9, 1, 7, 4, 8])

### Numpy Functions

In [19]:
# works like range() function
np.arange(0, 25, 5)

array([ 0,  5, 10, 15, 20])

In [20]:
# partitions the range according the third parameter
# includes both, start as well as end
np.linspace(0, 25, 5)

array([  0.  ,   6.25,  12.5 ,  18.75,  25.  ])

In [21]:
np.zeros(6)

array([ 0.,  0.,  0.,  0.,  0.,  0.])

In [22]:
np.ones(6)

array([ 1.,  1.,  1.,  1.,  1.,  1.])

In [23]:
np.sin([1, 2, 3, 4, 5, 6])

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ])

### Numpy Methods

In [24]:
a = np.array([1, 2, 3, 4, 5, 6])
a.sum()

21

In [25]:
a.prod()

720

In [26]:
a.mean()

3.5

In [27]:
a.max()

6

In [28]:
a.min()

1

In [29]:
# data type of a is int
a.fill(4.6)
a

array([4, 4, 4, 4, 4, 4])

In [30]:
# set all values in an array using fill()
a.fill(0)
a

array([0, 0, 0, 0, 0, 0])

In [31]:
a = a.reshape(2, 3)
a

array([[0, 0, 0],
       [0, 0, 0]])

In [32]:
a = a.flatten()
a

array([0, 0, 0, 0, 0, 0])

### Multi-dimensional Arrays

In [33]:
c = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [34]:
print(c.shape)       # number of rows and columns
print(c.nbytes)      # return the number of bytes used by the data portion of the array

(2, 5)
40


In [35]:
c[1][2]

8

In [36]:
# reshape method can be used with these options to give array a desired shape
r = np.arange(30)
r = r.reshape(5,6)
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [37]:
r[-1, -1]           # Unlike list, multiple parameters can be passed in single bracket to locate an element in the array. 

29

In [38]:
r[1, 1]

7

In [39]:
r[2, 1:]

array([13, 14, 15, 16, 17])

In [40]:
r[:1, :1]

array([[0]])

In [41]:
r[:, 2] = 100      # targeting a column
r

array([[  0,   1, 100,   3,   4,   5],
       [  6,   7, 100,   9,  10,  11],
       [ 12,  13, 100,  15,  16,  17],
       [ 18,  19, 100,  21,  22,  23],
       [ 24,  25, 100,  27,  28,  29]])

In [42]:
r % 3 == 0          # values divisible by 3

array([[ True, False, False,  True, False, False],
       [ True, False, False,  True, False, False],
       [ True, False, False,  True, False, False],
       [ True, False, False,  True, False, False],
       [ True, False, False,  True, False, False]], dtype=bool)

In [43]:
r[r % 3 == 0]       # Using above mask/condition to get the values.

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])